<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>RangeSlider.Avalonia</Title>
        <Authors>Dmitry Nizhebovsky</Authors>
        <Description>A range slider control for AvaloniaUI</Description>
        <PackageProjectUrl>https://github.com/DmitryNizhebovsky/Avalonia.RangeSlider</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/DmitryNizhebovsky/Avalonia.RangeSlider.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>controls range-slider cross-platform avalonia avaloniaui csharp c-sharp ui</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Version>3.0.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="" />
        <None Include="../LICENSE.md" Pack="true" PackagePath="" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.4" />
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="**/*.xaml" />
    </ItemGroup>

</Project>