name: BuildAndPublish

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
      - "**/LICENSE.md"
      - "**/.gitattributes"
      - "**/.gitignore"
      - "Images/**"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build RangeSlider.Avalonia --configuration Release --no-restore
        
      - name: Pack
        run: dotnet pack RangeSlider.Avalonia --configuration Release --no-build
        
      - name: Publish to NuGet.org
        run: |
          dotnet nuget push "RangeSlider.Avalonia/bin/Release/*.nupkg" \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
          
      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
          --api-key "${{ secrets.GITHUB_TOKEN }}" \
          --source https://nuget.pkg.github.com/DmitryNizhebovsky/index.json \
          --skip-duplicate